// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgrRwRrFBbRJen_WBYJI1vAsXibvdOz3I',
    appId: '1:284777712530:web:3bfd992fb5e89c43a9cf4b',
    messagingSenderId: '284777712530',
    projectId: 'crafty-bay-318a6',
    authDomain: 'crafty-bay-318a6.firebaseapp.com',
    storageBucket: 'crafty-bay-318a6.firebasestorage.app',
    measurementId: 'G-03S9480NMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABDiQORcAa2f056uCAFTzDUg4vEzjCXio',
    appId: '1:284777712530:android:f12d29404e91e33ba9cf4b',
    messagingSenderId: '284777712530',
    projectId: 'crafty-bay-318a6',
    storageBucket: 'crafty-bay-318a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVmFUkSjpXQLxP4Jw8s66POcGu9Lam8U',
    appId: '1:284777712530:ios:8dd22a0bb96564a9a9cf4b',
    messagingSenderId: '284777712530',
    projectId: 'crafty-bay-318a6',
    storageBucket: 'crafty-bay-318a6.firebasestorage.app',
    iosBundleId: 'com.example.ghoroaMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaVmFUkSjpXQLxP4Jw8s66POcGu9Lam8U',
    appId: '1:284777712530:ios:8dd22a0bb96564a9a9cf4b',
    messagingSenderId: '284777712530',
    projectId: 'crafty-bay-318a6',
    storageBucket: 'crafty-bay-318a6.firebasestorage.app',
    iosBundleId: 'com.example.ghoroaMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgrRwRrFBbRJen_WBYJI1vAsXibvdOz3I',
    appId: '1:284777712530:web:18cbfebb2b54c262a9cf4b',
    messagingSenderId: '284777712530',
    projectId: 'crafty-bay-318a6',
    authDomain: 'crafty-bay-318a6.firebaseapp.com',
    storageBucket: 'crafty-bay-318a6.firebasestorage.app',
    measurementId: 'G-N4LKTXREN9',
  );
}
